# Generated by Django 4.2.1 on 2024-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
                ("birthday", models.TextField(max_length=5)),
                ("telephone", models.IntegerField()),
            ],
        ),
    ]
