# Generated by Django 4.2.1 on 2024-11-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_agenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="RegUser",),
    ]
