# Generated by Django 4.2.1 on 2024-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id_serv", models.AutoField(primary_key=True, serialize=False)),
                ("name_serv", models.CharField(max_length=255)),
                ("price_serv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_serv", models.DurationField()),
            ],
        ),
    ]
