# Generated by Django 4.2.1 on 2024-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="time_serv",
            field=models.DurationField(default="00:00:00"),
        ),
    ]
