# Generated by Django 4.2.1 on 2024-12-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0002_alter_services_time_serv"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="time_serv",),
    ]
