# Generated by Django 4.2.1 on 2024-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0005_alter_services_min_serv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="min_serv",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
