# Generated by Django 4.2.1 on 2025-01-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0006_alter_services_min_serv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="min_serv",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
