# Generated by Django 4.2.1 on 2025-02-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_agenda", "0002_rename_user_reguser"),
        ("app_services", "0007_alter_services_min_serv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id_reserv", models.AutoField(primary_key=True, serialize=False)),
                ("date_reserv", models.DateField()),
                (
                    "reserv_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_agenda.reguser",
                    ),
                ),
                (
                    "service_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_services.services",
                    ),
                ),
            ],
        ),
    ]
